services:
  - type: web
    name: nurse-chat-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python ingest.py"
    startCommand: "cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: GROQ_API_KEY
        sync: false
